_BASE_: "Base-RCNN-FPN.yaml"

MODEL:
  MASK_ON: True
  DEVICE: cuda:0
  WEIGHTS: detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 1
    BATCH_SIZE_PER_IMAGE: 8
    SCORE_THRESH_TEST: 0.8
  ANCHOR_GENERATOR:
    SIZES: [[256, 512, 750]]
    ASPECT_RATIOS: [[0.5, 1.0]]
    ANGLES: [[0]]




INPUT:
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TRAIN: (1000,)
  MAX_SIZE_TRAIN: 2000
  MIN_SIZE_TEST: 1000
  MAX_SIZE_TEST: 2000

SOLVER:
  IMS_PER_BATCH: 1
  MAX_ITER: 15000
  WARMUP_ITERS: 1000
  BASE_LR: 0.002
  STEPS: (2000, 5000, 10000, 14000)
  CHECKPOINT_PERIOD: 3000


DATASETS:
  TRAIN: ("container_train",)
  TEST: ("container_val", )

TEST:
  EVAL_PERIOD: 3000

DATALOADER:
  NUM_WORKERS: 0
  FILTER_EMPTY_ANNOTATIONS: True


OUTPUT_DIR: outputs


