_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  MASK_ON: True
  DEVICE: cuda:0
  WEIGHTS: detectron2://ImageNetPretrained/MSRA/R-50.pkl
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 1
    BATCH_SIZE_PER_IMAGE: 128


DATASETS:
  TRAIN: ("container_train",)
  TEST: ()
DATALOADER:
  NUM_WORKERS: 1

SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.00025
  MAX_ITER: 500
  STEPS: [] # do not perform decay on the learning rate

OUTPUT_DIR: outputs