_BASE_: "Base-RCNN-FPN.yaml"

MODEL:
  MASK_ON: True
  DEVICE: cuda:0
  WEIGHTS: detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 1
    SCORE_THRESH_TEST: 0.98
  ANCHOR_GENERATOR:
    ASPECT_RATIOS: [[0.5, 0.7, 1.0]]
    SIZES: [[128, 256, 512, 750]]

INPUT:
  MIN_SIZE_TRAIN_SAMPLING: "range"
  MIN_SIZE_TRAIN: (800, 1200)
  MAX_SIZE_TRAIN: 4000
  MIN_SIZE_TEST: 1000
  MAX_SIZE_TEST: 2000


SOLVER:
  IMS_PER_BATCH: 4
  MAX_ITER: 13000
  WARMUP_ITERS: 1000
  BASE_LR: 0.005
  STEPS: (3000, 7000, 12000)
  CHECKPOINT_PERIOD: 1000
  AMP:
    ENABLED: True


DATASETS:
  TRAIN: ("container_train",)
  TEST: ("container_val", )

TEST:
  EVAL_PERIOD: 1000

DATALOADER:
  NUM_WORKERS: 1
  FILTER_EMPTY_ANNOTATIONS: False


OUTPUT_DIR: outputs


