_BASE_: "temp.yaml"
MODEL:
  DEVICE: cuda:0
  WEIGHTS: output_28feb/model_final.pth
  ROI_HEADS:
    SCORE_THRESH_TEST: 0.95

OUTPUT_DIR: outputs

INPUT:
  MIN_SIZE_TRAIN_SAMPLING: "range"
  MIN_SIZE_TRAIN: (800,1200)
  MAX_SIZE_TRAIN: 4000
  MIN_SIZE_TEST: 1000
  MAX_SIZE_TEST: 4000
  CROP:
    ENABLED: True
    TYPE: "relative_range"
    SIZE: [0.50, 0.50]
  RANDOM_FLIP: "horizontal"
