_BASE_: "container_detection_train.yaml"
SOLVER:
  IMS_PER_BATCH: 2
  MAX_ITER: 1000
  BASE_LR: 0.00025

MODEL:
  ROI_HEADS:
    NUM_CLASSES: 1
    BATCH_SIZE_PER_IMAGE: 28

INPUT:
  MIN_SIZE_TRAIN: (1000,)
  MAX_SIZE_TRAIN: 4000
  MIN_SIZE_TEST: 0
  MAX_SIZE_TEST: 4000

